site_name: ZipStrain




theme:
  name: "material"

nav:
  - index.md
  - installation.md
  - Tutorial.md
  - NextflowPipeline.md
  - cli.md
  - api.md
  


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 4
            show_root_toc_entry: true
